### ISSUE TITLE
Add repacking support to the 2014 client

### ISSUE THREAD

**Issue by bobtheskeeter** [x1nixmzeng/z3ResEx#8]
Hey,
I was wondering if there were any possibility at all to make your RAFWizard program to patch the “latest” client 2014 version. 

I see that this supports the latest NA files but I was wondering if you’d add support for NA files on your repacking tool too. As we are desperate to revive the game.

Now I’m no expert in coding so I have no idea how to reverse engineer your program to repack the unpacked files back into the RaiderZ NA client. 
But I am hoping you’ll be the savior of this sadly dying community.

Sincerely
Bob

**Comment by x1nixmzeng** [comment]
Hey Bob, unfortunately the unpacking process is one-way due to the crypto method RaiderZ uses.

To repack files, you're best solution is to modify the game client to read files in a different way. This was done for GunZ several years ago

**Comment by bobtheskeeter** [comment]
It'd be nice if you could provide with any suggestions of where to start, and what to do/look for. As I'm not experienced in any way, but nor do I want to be a brat in a way that I'm expecting you to help me finish this 100%.

Just like, links, terms etc. for stuff I can maybe find articles detailing how-to read files in a different way. If money is something that could motivate you, I'd be happy to provide. And still pay for making this open source code.

**Comment by x1nixmzeng** [comment]
I'm motivated by ideas, so what's your goal with this old client? It looks like source code was released, so why not using that instead - it would give the flexibility of adding any new features you'd need?

Otherwise, getting started at patching the game client requires a mid-level understanding of assembly, a decent debugger (I was using http://www.ollydbg.de/) and a rough understanding of the OpenFile/ReadFile WinAPI. The game files usually include "containers" with multiple files, which means you can't just bypass the decryption step.

I'm on discord if you want to drop a message to `x1nixmzeng#1074`
